### ISSUE TITLE
missing import of a datatype in gmm.py

### ISSUE THREAD

**Issue by jankounchained** [x-tabdeveloping/turftopic#2]
in models/gmm.py, the `base.Encoder` data type is not imported.
Line 47 then raises an error, because `Encoder` is unknown.

Fix:
change Line 9 to `from turftopic.base import ContextualModel, Encoder`

I can't do it myself, don't have push permission

**Comment by x-tabdeveloping** [comment]
You can fork the repo, push to your own fork, then submit a pull request. I can also try to make you collaborator

**Comment by x-tabdeveloping** [comment]
I have pushed out a new release, it should work just fine
