### ISSUE TITLE
Docs deployment failing

### ISSUE THREAD

**Issue by rbroc** [x-tabdeveloping/turftopic#30]
Docs deployment failing as there are some issues when installing extras in the docs deployment workflow.

We get this warning:
`WARNING: turftopic 0.2.12 does not provide the extra 'docs'`

which is related to `pip install turftopic[docs,pyro-ppl]`

**Comment by rbroc** [comment]
Not sure if relevant, but in `pyproject.toml`, we have `version = "0.2.11"` -- not sure if this can be as simple as a weird issue with version mismatch.

**Comment by x-tabdeveloping** [comment]
@jankounchained Can you look into this?

**Comment by jankounchained** [comment]
fixed.
