### ISSUE TITLE
what if FastICA doesn't converge?

### ISSUE THREAD

**Issue by jankounchained** [x-tabdeveloping/turftopic#37]
this might be a more general problem with giving arguments to the underlying ICA algorithm.
for example:
- increase n_inter
- giving it a random state so you get exactly the same S3 model when you run it twice (nice for deployment)

**Comment by x-tabdeveloping** [comment]
I'm on it. Though I would argue that if the model doesn't converge after 200 iterations, it is probably a sign of something (there is no clear pattern in the data)
